# 请将你在聊天记录中最终确认有效的规则粘贴到这里
# 以下仅为示例，请务必替换为你自己的规则！
rules:
  # --- 文件和目录操作 ---
  - pattern: "在桌面新建文档"
    command: "touch ~/桌面/新建文档.txt"
  - pattern: "在桌面创建资料文件夹"
    command: "mkdir ~/桌面/资料"
  - pattern: "查看桌面文件"
    command: "ls -al ~/桌面"
  - pattern: "查看当前目录文件"
    command: "ls -alh"
  # - pattern: "显示桌面配置内容"
  #   command: "cat ~/桌面/配置.txt" # 确保文件存在
  # - pattern: "编辑桌面笔记"
  #   command: "nano ~/桌面/笔记.md" # 确保文件存在
  - pattern: "删除桌面的临时文件"
    command: "rm -i ~/桌面/临时文件.txt"
  - pattern: "删除桌面的临时资料夹"
    command: "rm -ri ~/桌面/临时资料"
  # - pattern: "复制桌面报告到下载"
  #   command: "cp ~/桌面/报告.docx ~/下载/" # 确保文件存在
  # - pattern: "移动下载图片到图片文件夹"
  #   command: "mv ~/下载/图片.jpg ~/图片/" # 确保文件和目标目录存在

  # --- 压缩与解压 ---
  # - pattern: "压缩桌面项目A文件夹"
  #   command: "zip -r ~/桌面/项目A.zip ~/桌面/项目A" # 确保目录存在
  - pattern: "解压下载的压缩包" # 假设解压到下载目录
    command: "unzip ~/下载/*.zip -d ~/下载/" # 注意 *.zip 可能解压多个

  # --- 系统信息 ---
  - pattern: "显示当前时间"
    command: "date"
  - pattern: "查看磁盘空间"
    command: "df -h"
  - pattern: "查看内存使用情况"
    command: "free -h"
  - pattern: "查看我的IP地址"
    command: "ip addr show | grep 'inet ' | grep -v '127.0.0.1'"

  # --- 系统控制 (需要 sudo 权限) ---
  - pattern: "重启电脑"
    command: "sudo reboot"
  - pattern: "关机"
    command: "sudo poweroff"

  # --- 软件管理 (需要 sudo 权限) ---
  - pattern: "更新软件列表"
    command: "sudo apt update"
  - pattern: "升级所有软件"
    command: "sudo apt upgrade -y"

  # --- 网络工具 ---
  - pattern: "ping百度"
    command: "ping -c 4 baidu.com"

  # --- 其他 ---
  - pattern: "打开浏览器"
    command: "xdg-open https://www.google.com &" # 使用 xdg-open 更通用
  - pattern: "打开文件管理器"
    command: "xdg-open ~/ &"
  - pattern: "打开终端"
    command: "gnome-terminal &" # 或者你的终端模拟器命令

  # --- 身份验证 (示例，需要 oathtool 和配置密钥) ---
  # - pattern: "生成 TOTP 代码"
  #   command: "oathtool --totp --base32 JBSWY3DPEHPK3PXP" # 替换为你的真实密钥！
